algoritmo "exercicioAP1Revisao11 - tabuadaN"
// Ler um valor inteiro (aceitar somente valores entre 1 e 10) e escrever
// a tabuada de 1 a 10 do valor lido.
var
   n, contador: Inteiro
inicio
      Repita
         Escreva("Digite um número: ")
         Leia(n)
      Ate ((n >= 1) E (n <= 10))
      
      Para contador de 1 ate 10 faca
           Escreval(n, " x ", contador, " = ", n * contador)
      FimPara

fimalgoritmo
