algoritmo "exercicioAP1Revisao09 - intervalo"
// Ler um valor N e imprimir todos os valores inteiros entre 1 (inclusive)
// e N (inclusive). Considere que o N será sempre maior que ZERO.
var
   n, contador: Inteiro
inicio
      Repita
         Escreva("Digite um número qualquer: ")
         Leia(n)
      Ate n > 0
      
      Para contador de 1 ate n faca
           Escreva(contador)
      FimPara

fimalgoritmo
