algoritmo "exercicioEstruturaDeRepeticao08 - 1AteN"
// Ler um valor N e imprimir todos os valores inteiros entre 1 (inclusive)
// e N (inclusive). Considere que o N será sempre maior que ZERO.

var
   N, contador: Inteiro
inicio
      Repita
            Escreva("Digite um número: ")
            Leia(N)
      Ate N > 0
      
      Escreval()
      Para contador de 1 ate N faca
           Escreval(contador)
      FimPara
fimalgoritmo
