algoritmo "exercicioEstruturaDeRepeticao09 - tabuada"
// Escreva um algoritmo que calcule e imprima a tabuada de um número
// de 1 a 10 dado pelo usuário
var
   N, contador: Inteiro
inicio
      Repita
            Escreva("Digite um número entre 1 e 10: ")
            Leia(N)
      Ate (N >= 1) E (N <= 10)
      
      Escreval()
      Para contador de 1 ate 10 faca
           Escreval(N, " x", contador, " =", N * contador)
      FimPara
fimalgoritmo
