algoritmo "exercicioComSelecaoEncadeada01 - positivo"
// Ler um valor e escrever se é positivo, negativo ou zero
var
   valor: Inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(valor)

      Escreval()
      Escreva("Valor ")
      Se (valor >= 0) entao
         Se (valor <> 0) entao
            Escreval("Positivo!!")
         Senao
              Escreval("Nulo!!")
         FimSe
      Senao
         Escreval("Negativo!!")
      FimSe
fimalgoritmo
