algoritmo "exercicioComSelecao01 - comparacao"
// Ler um valor e escrever a mensagem É MAIOR QUE 10!
// Se o valor lido for maior que 10, caso contrário,
// escrever NÃO É MAIOR QUE 10!
var
   x: inteiro
inicio
      escreva("Digite um número: ")
      leia(x)
      Se (x > 10) entao
         escreva ("É MAIOR QUE 10!")
      Senao
           escreva("NÃO É MAIOR QUE 10!")
      FimSe
fimalgoritmo
