algoritmo "Partial_Assessment_01_Review_Exercise_08 - 10 To 1"

// Write an algorithm to print the numbers from 1 (inclusive) to 10 (inclusive)
// in descending order.

var
      start, end, counter: Inteiro

Inicio
      start <- 10
      end <- 1
      counter <- start
      
      Escreval("Welcome!!!")
      Escreval("Let's count the numbers from ", start, " to ", end, "!!")

      Para counter de start ate end passo -1 Faca
            Escreva(counter, " ")
      FimPara
FimAlgoritmo
