algoritmo "Partial_Assessment_01_Review_Exercise_07 - 1 To 10"

// Write an algorithm to print the numbers from 1 (inclusive) to 10 (inclusive)
// in ascending order.

var
      start, end, counter: Inteiro

Inicio
      start <- 1
      end <- 10
      counter <- start

      Escreval("Welcome!!!")
      Escreval("Let's count the numbers from ", start, " to ", end, "!!")

      Para counter de start ate end Faca
            Escreva(counter, " ")
      FimPara
FimAlgoritmo
